services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./.volumes/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=digitalbunch
      - MONGO_INITDB_ROOT_PASSWORD=digitalbunch
    networks:
      - app_network
networks:
  app_network:
